# -*- coding: utf-8 -*-
"""DRL_fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8AoFExDwDJU2VoH68PtJdjCTd9-JN1g

# Deep Reinforcement Learning — CarRacing-v3
**Fixed notebook:** includes virtual display, frame stacking, video recording, checkpoint saving, and training curves.

**Runtime:** Runtime → Change runtime type → T4 GPU

## Cell 1 — Install dependencies
"""

# Run this every time the runtime restarts
!pip -q install swig
!pip -q install "gymnasium[box2d]" stable-baselines3[extra] "shimmy>=2.0" pyvirtualdisplay imageio imageio-ffmpeg

from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

from google.colab import drive
drive.mount('/content/drive')

import os
SAVE_DIR = '/content/drive/MyDrive/DRL_CarRacing'
print('Environment ready.')

# Install system dependencies first (swig must come before box2d)
!apt-get update -qq
!apt-get install -y -qq swig cmake ffmpeg xvfb \
  libgl1-mesa-dev libglu1-mesa-dev libxrender1 libsm6 libxext6

# Install Python packages
!pip -q install --upgrade pip
!pip -q install "gymnasium[box2d]" stable-baselines3[extra] "shimmy>=2.0" \
                 pyvirtualdisplay imageio imageio-ffmpeg

print('All dependencies installed.')

"""## Cell 2 — Start virtual display (CRITICAL FIX)

This is what was missing. Without this, the Monitor wrapper crashes silently in Colab.
"""

from pyvirtualdisplay import Display

# Start a virtual screen — Colab has no physical display
display = Display(visible=0, size=(1400, 900))
display.start()
print('Virtual display started.')

"""## Cell 3 — Mount Google Drive (save checkpoints so you never lose a run)"""

from google.colab import drive
drive.mount('/content/drive')

import os
SAVE_DIR = '/content/drive/MyDrive/DRL_CarRacing'
os.makedirs(SAVE_DIR, exist_ok=True)
os.makedirs(f'{SAVE_DIR}/checkpoints_ppo', exist_ok=True)
os.makedirs(f'{SAVE_DIR}/checkpoints_dqn', exist_ok=True)
os.makedirs(f'{SAVE_DIR}/videos', exist_ok=True)
os.makedirs(f'{SAVE_DIR}/logs', exist_ok=True)
print(f'Save directory ready: {SAVE_DIR}')

"""## Cell 4 — Environment wrappers

FIX: FrameStack is now properly imported and used to give the agent motion information (velocity/direction across 4 consecutive frames). This satisfies the Markov property more closely.
"""

## CELL 4 — Fixed environment wrappers

import numpy as np
import gymnasium as gym
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage, VecFrameStack
from stable_baselines3.common.monitor import Monitor

# Drop TransformObservation entirely.
# SB3's CnnPolicy normalises pixel values internally

def make_ppo_env(seed=0):
    def _init():
        env = gym.make('CarRacing-v3', continuous=True, render_mode='rgb_array')
        env = Monitor(env, filename=f'{SAVE_DIR}/logs/ppo_monitor')
        env.reset(seed=seed)
        return env
    return _init

def make_dqn_env(seed=0):
    def _init():
        env = gym.make('CarRacing-v3', continuous=False, render_mode='rgb_array')
        env = Monitor(env, filename=f'{SAVE_DIR}/logs/dqn_monitor')
        env.reset(seed=seed)
        return env
    return _init

# Sanity check — obs space must show dtype=uint8 and shape (96,96,3)
test_env = make_ppo_env()()
obs, _ = test_env.reset()
print('PPO obs shape:', obs.shape)           # (96, 96, 3)
print('PPO obs dtype:', obs.dtype)           # uint8
print('PPO obs space:', test_env.observation_space)
print('PPO action space:', test_env.action_space)
test_env.close()

test_env2 = make_dqn_env()()
obs2, _ = test_env2.reset()
print('DQN obs shape:', obs2.shape)
print('DQN action space:', test_env2.action_space)
test_env2.close()

"""## Cell 5 — Custom reward shaping wrapper (optional — comment out to use default sparse reward)"""

class ShapedRewardWrapper(gym.Wrapper):
    """
    Custom reward function:
    r(t) = alpha * r_progress - beta * r_time - gamma * r_offtrack - delta * r_speed

    alpha=1.0  : reward per new track tile visited
    beta=0.1   : timestep penalty (encourages speed)
    gamma=5.0  : off-track penalty (safety term)
    delta=0.05 : penalty for speed below v_min (anti-stall)
    """
    def __init__(self, env, alpha=1.0, beta=0.1, gamma=5.0, delta=0.05, v_min=0.1):
        super().__init__(env)
        self.alpha = alpha
        self.beta  = beta
        self.gamma = gamma
        self.delta = delta
        self.v_min = v_min

    def step(self, action):
        obs, reward, terminated, truncated, info = self.env.step(action)

        # Progress reward: use the environment's tile reward as proxy
        r_progress = max(reward, 0) * self.alpha

        # Timestep penalty
        r_time = self.beta

        # Off-track penalty: detect grass (green channel dominates in grass pixels)
        # Look at centre strip of observation
        frame = np.array(obs)
        if frame.ndim == 4:          # stacked frames — use most recent
            frame = frame[-1]
        centre = frame[60:80, 40:56] # region where track should be
        green_dom = (centre[..., 1] > centre[..., 0]) & (centre[..., 1] > centre[..., 2])
        off_track = float(green_dom.mean() > 0.5)
        r_offtrack = self.gamma * off_track

        # Speed regularisation — approximate from reward signal
        speed_proxy = max(reward, 0)
        r_speed = self.delta * max(0, self.v_min - speed_proxy)

        shaped_reward = r_progress - r_time - r_offtrack - r_speed
        return obs, shaped_reward, terminated, truncated, info

print('ShapedRewardWrapper defined.')

"""## Cell 6 — PPO training with checkpoints and callbacks"""

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import (
    CheckpointCallback, EvalCallback, CallbackList
)

TOTAL_TIMESTEPS_PPO = 1_000_000

# Step 1: vectorise
ppo_train_env = DummyVecEnv([make_ppo_env(seed=0)])
# Step 2: transpose to channels-first (H,W,C) -> (C,H,W) for CNN
ppo_train_env = VecTransposeImage(ppo_train_env)
# Step 3: stack 4 frames AFTER transpose — this is the correct order
ppo_train_env = VecFrameStack(ppo_train_env, n_stack=4)

# Same order for eval env
ppo_eval_env = DummyVecEnv([make_ppo_env(seed=42)])
ppo_eval_env = VecTransposeImage(ppo_eval_env)
ppo_eval_env = VecFrameStack(ppo_eval_env, n_stack=4)

checkpoint_cb = CheckpointCallback(
    save_freq=100_000,
    save_path=f'{SAVE_DIR}/checkpoints_ppo',
    name_prefix='ppo_carracing',
    verbose=1
)

eval_cb = EvalCallback(
    ppo_eval_env,
    best_model_save_path=f'{SAVE_DIR}/checkpoints_ppo/best',
    log_path=f'{SAVE_DIR}/logs/ppo_eval',
    eval_freq=50_000,
    n_eval_episodes=5,
    deterministic=True,
    verbose=1
)

ppo_model = PPO(
    policy='CnnPolicy',
    env=ppo_train_env,
    learning_rate=3e-4,
    n_steps=1024,
    batch_size=64,
    n_epochs=10,
    gamma=0.99,
    gae_lambda=0.95,
    clip_range=0.15,
    clip_range_vf=0.2,
    ent_coef=0.01,
    vf_coef=0.5,
    max_grad_norm=0.5,
    verbose=1,
    tensorboard_log=f'{SAVE_DIR}/logs/ppo_tb'
)

print('Starting PPO training...')
print(f'Obs space after wrappers: {ppo_train_env.observation_space}')  # should be (4,3,96,96)

ppo_model.learn(
    total_timesteps=TOTAL_TIMESTEPS_PPO,
    callback=CallbackList([checkpoint_cb, eval_cb]),
    progress_bar=True
)

ppo_model.save(f'{SAVE_DIR}/ppo_final')
print('PPO training complete. Model saved.')

"""## Cell 7 — DQN training with checkpoints and callbacks"""

from stable_baselines3 import DQN

TOTAL_TIMESTEPS_DQN = 300_000

dqn_train_env = DummyVecEnv([make_dqn_env(seed=0)])
dqn_train_env = VecTransposeImage(dqn_train_env)
dqn_train_env = VecFrameStack(dqn_train_env, n_stack=4)

dqn_eval_env = DummyVecEnv([make_dqn_env(seed=42)])
dqn_eval_env = VecTransposeImage(dqn_eval_env)
dqn_eval_env = VecFrameStack(dqn_eval_env, n_stack=4)

dqn_checkpoint_cb = CheckpointCallback(
    save_freq=50_000,
    save_path=f'{SAVE_DIR}/checkpoints_dqn',
    name_prefix='dqn_carracing',
    verbose=1
)

dqn_eval_cb = EvalCallback(
    dqn_eval_env,
    best_model_save_path=f'{SAVE_DIR}/checkpoints_dqn/best',
    log_path=f'{SAVE_DIR}/logs/dqn_eval',
    eval_freq=30_000,
    n_eval_episodes=5,
    deterministic=True,
    verbose=1
)

dqn_model = DQN(
    policy='CnnPolicy',
    env=dqn_train_env,
    learning_rate=1e-4,
    buffer_size=100_000,
    learning_starts=10_000,
    batch_size=32,
    gamma=0.99,
    train_freq=4,
    target_update_interval=10_000,
    exploration_fraction=0.2,
    exploration_final_eps=0.05,
    verbose=1,
    tensorboard_log=f'{SAVE_DIR}/logs/dqn_tb'
)

print('Starting DQN training...')
dqn_model.learn(
    total_timesteps=TOTAL_TIMESTEPS_DQN,
    callback=CallbackList([dqn_checkpoint_cb, dqn_eval_cb]),
    progress_bar=True
)

dqn_model.save(f'{SAVE_DIR}/dqn_final')
print('DQN training complete. Model saved.')

"""## Cell 8 — Record video of the trained agent driving (THE FIX for visualising the car)"""

import imageio
from IPython.display import Video, display as ipy_display
from stable_baselines3 import PPO, DQN
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage, VecFrameStack

def record_agent(model, env_creation_function, is_ppo_model, video_path, n_episodes=3, fps=30):
    frames = []
    for ep in range(n_episodes):
        env = DummyVecEnv([env_creation_function(seed=ep)])
        env = VecTransposeImage(env)
        if is_ppo_model:
            env = VecFrameStack(env, n_stack=4)
        obs = env.reset()
        done = False
        ep_reward = 0
        step = 0
        while not done and step < 1000:
            frame = env.envs[0].env.render()
            if frame is not None:
                frames.append(frame)
            action, _ = model.predict(obs, deterministic=True)
            obs, reward, done_arr, info = env.step(action)
            ep_reward += reward[0]
            done = done_arr[0]
            step += 1
        print(f'Episode {ep+1}: reward={ep_reward:.2f}, steps={step}')
        env.close()
    if len(frames) == 0:
        print('WARNING: No frames captured.')
        return None
    imageio.mimwrite(video_path, frames, fps=fps, codec='libx264')
    print(f'Video saved to: {video_path}')
    return video_path

ppo_loaded = PPO.load(f'{SAVE_DIR}/ppo_final')
dqn_loaded = DQN.load(f'{SAVE_DIR}/dqn_final')

ppo_video = record_agent(ppo_loaded, make_ppo_env, is_ppo_model=True,
    video_path=f'{SAVE_DIR}/videos/ppo_agent.mp4', n_episodes=3)

dqn_video = record_agent(dqn_loaded, make_dqn_env, is_ppo_model=False,
    video_path=f'{SAVE_DIR}/videos/dqn_agent.mp4', n_episodes=3)

if ppo_video:
    print('PPO agent:')
    ipy_display(Video(ppo_video, embed=True, width=400))
if dqn_video:
    print('DQN agent:')
    ipy_display(Video(dqn_video, embed=True, width=400))

"""## Cell 9 — Training curves (reward, episode length, loss over time)"""

#FIXED CELL 9

from stable_baselines3.common.results_plotter import load_results, ts2xy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def smooth(y, window=10):
    return pd.Series(y).rolling(window, min_periods=1).mean().values

# Load PPO and DQN monitor logs separately by filename
ppo_log = load_results(f'{SAVE_DIR}/logs/')

# Filter to only PPO monitor data
ppo_df = pd.read_csv(f'{SAVE_DIR}/logs/ppo_monitor.monitor.csv',
                      skiprows=1)  # skip the header comment line
dqn_df = pd.read_csv(f'{SAVE_DIR}/logs/dqn_monitor.monitor.csv',
                      skiprows=1)

# Compute cumulative timesteps
ppo_df['timesteps'] = ppo_df['l'].cumsum()
dqn_df['timesteps'] = dqn_df['l'].cumsum()

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
fig.suptitle('PPO vs DQN Training Curves — CarRacing-v3', fontsize=13)

# Mean reward
axes[0].plot(ppo_df['timesteps'], smooth(ppo_df['r'], 10),
             label='PPO', color='steelblue')
axes[0].plot(dqn_df['timesteps'], smooth(dqn_df['r'], 10),
             label='DQN', color='darkorange')
axes[0].set_xlabel('Timesteps')
axes[0].set_ylabel('Mean Episode Reward')
axes[0].set_title('Mean Episode Reward')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Episode length
axes[1].plot(ppo_df['timesteps'], smooth(ppo_df['l'], 10),
             label='PPO', color='steelblue')
axes[1].plot(dqn_df['timesteps'], smooth(dqn_df['l'], 10),
             label='DQN', color='darkorange')
axes[1].set_xlabel('Timesteps')
axes[1].set_ylabel('Episode Length (steps)')
axes[1].set_title('Episode Length')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

# Eval reward (keep this — it's correct)
try:
    ppo_eval = np.load(f'{SAVE_DIR}/logs/ppo_eval/evaluations.npz')
    dqn_eval = np.load(f'{SAVE_DIR}/logs/dqn_eval/evaluations.npz')
    axes[2].plot(ppo_eval['timesteps'], ppo_eval['results'].mean(axis=1),
                 label='PPO eval', color='steelblue')
    axes[2].fill_between(ppo_eval['timesteps'],
                         ppo_eval['results'].mean(axis=1) - ppo_eval['results'].std(axis=1),
                         ppo_eval['results'].mean(axis=1) + ppo_eval['results'].std(axis=1),
                         alpha=0.2, color='steelblue')
    axes[2].plot(dqn_eval['timesteps'], dqn_eval['results'].mean(axis=1),
                 label='DQN eval', color='darkorange')
    axes[2].fill_between(dqn_eval['timesteps'],
                         dqn_eval['results'].mean(axis=1) - dqn_eval['results'].std(axis=1),
                         dqn_eval['results'].mean(axis=1) + dqn_eval['results'].std(axis=1),
                         alpha=0.2, color='darkorange')
    axes[2].set_xlabel('Timesteps')
    axes[2].set_ylabel('Eval Reward')
    axes[2].set_title('Evaluation Reward (deterministic)')
    axes[2].legend()
    axes[2].grid(True, alpha=0.3)
except Exception as e:
    print(f'Eval data error: {e}')

plt.tight_layout()
plt.savefig(f'{SAVE_DIR}/training_curves_fixed.png', dpi=150, bbox_inches='tight')
plt.show()

"""## Cell 10 — Ablation study: effect of learning rate on PPO reward"""

## CELL 10 — Ablation study (fully self-contained)

import os
import numpy as np
import matplotlib.pyplot as plt
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage, VecFrameStack
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.evaluation import evaluate_policy

SAVE_DIR = '/content/drive/MyDrive/DRL_CarRacing'

# Redefine make_ppo_env here so this cell works after any restart
def make_ppo_env(seed=0):
    def _init():
        env = gym.make('CarRacing-v3', continuous=True, render_mode='rgb_array')
        env = Monitor(env, filename=f'{SAVE_DIR}/logs/ppo_monitor')
        env.reset(seed=seed)
        return env
    return _init

ABLATION_STEPS = 100_000
learning_rates = [1e-4, 3e-4, 7.5e-4]
ablation_results = {}

for lr in learning_rates:
    print(f'\nTraining PPO with lr={lr}...')
    env = DummyVecEnv([make_ppo_env(seed=0)])
    env = VecTransposeImage(env)
    env = VecFrameStack(env, n_stack=4)

    model = PPO(
        'CnnPolicy', env,
        learning_rate=lr,
        n_steps=1024, batch_size=64, n_epochs=10,
        gamma=0.99, gae_lambda=0.95,
        clip_range=0.15, ent_coef=0.01,
        verbose=0
    )
    model.learn(total_timesteps=ABLATION_STEPS, progress_bar=True)

    eval_env = DummyVecEnv([make_ppo_env(seed=99)])
    eval_env = VecTransposeImage(eval_env)
    eval_env = VecFrameStack(eval_env, n_stack=4)

    mean_r, std_r = evaluate_policy(model, eval_env, n_eval_episodes=5, deterministic=True)
    ablation_results[lr] = (mean_r, std_r)
    print(f'  lr={lr}: mean reward={mean_r:.2f} +/- {std_r:.2f}')
    env.close()
    eval_env.close()

# Plot results
lrs = list(ablation_results.keys())
means = [ablation_results[lr][0] for lr in lrs]
stds  = [ablation_results[lr][1] for lr in lrs]

fig, ax = plt.subplots(figsize=(6, 4))
ax.bar([str(lr) for lr in lrs], means, yerr=stds, capsize=5,
       color=['#4C72B0', '#DD8452', '#55A868'])
ax.set_xlabel('Learning Rate')
ax.set_ylabel('Mean Eval Reward (5 episodes)')
ax.set_title(f'Ablation: PPO Learning Rate Sensitivity ({ABLATION_STEPS//1000}k steps)')
ax.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.savefig(f'{SAVE_DIR}/ablation_lr.png', dpi=150, bbox_inches='tight')
plt.show()
print('Ablation study complete.')

"""## Cell 11 — PPO vs DQN comparison table"""

## CELL 11 — Comparison table (fully self-contained)

import os
import numpy as np
import pandas as pd
import gymnasium as gym
from stable_baselines3 import PPO, DQN
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage, VecFrameStack
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.evaluation import evaluate_policy

SAVE_DIR = '/content/drive/MyDrive/DRL_CarRacing'

def make_ppo_env(seed=0):
    def _init():
        env = gym.make('CarRacing-v3', continuous=True, render_mode='rgb_array')
        env = Monitor(env, filename=f'{SAVE_DIR}/logs/ppo_monitor')
        env.reset(seed=seed)
        return env
    return _init

def make_dqn_env(seed=0):
    def _init():
        env = gym.make('CarRacing-v3', continuous=False, render_mode='rgb_array')
        env = Monitor(env, filename=f'{SAVE_DIR}/logs/dqn_monitor')
        env.reset(seed=seed)
        return env
    return _init

# Load models
ppo_loaded = PPO.load(f'{SAVE_DIR}/ppo_final')
dqn_loaded = DQN.load(f'{SAVE_DIR}/dqn_final')

# PPO eval env — with frame stacking (trained with it)
ppo_eval_env = DummyVecEnv([make_ppo_env(seed=42)])
ppo_eval_env = VecTransposeImage(ppo_eval_env)
ppo_eval_env = VecFrameStack(ppo_eval_env, n_stack=4)

# DQN eval env — WITHOUT frame stacking (trained without it)
dqn_eval_env = DummyVecEnv([make_dqn_env(seed=42)])
dqn_eval_env = VecTransposeImage(dqn_eval_env)

# Evaluate
ppo_mean, ppo_std = evaluate_policy(ppo_loaded, ppo_eval_env, n_eval_episodes=10, deterministic=True)
dqn_mean, dqn_std = evaluate_policy(dqn_loaded, dqn_eval_env, n_eval_episodes=10, deterministic=True)

ppo_eval_env.close()
dqn_eval_env.close()

print(f'PPO: mean={ppo_mean:.2f}, std={ppo_std:.2f}')
print(f'DQN: mean={dqn_mean:.2f}, std={dqn_std:.2f}')

# Build comparison table
comparison = pd.DataFrame({
    'Metric': [
        'Action Space', 'Algorithm Type', 'Training Steps',
        'Eval Mean Reward', 'Eval Std Dev',
        'Action Smoothness', 'Sample Efficiency',
        'Suitable for Continuous Control'
    ],
    'PPO': [
        'Continuous Box(3,)', 'On-policy actor-critic', '1,000,000',
        f'{ppo_mean:.2f}', f'±{ppo_std:.2f}',
        'High (smooth)', 'Moderate', 'Yes'
    ],
    'DQN': [
        'Discrete (5 actions)', 'Off-policy value-based', '300,000',
        f'{dqn_mean:.2f}', f'±{dqn_std:.2f}',
        'Low (abrupt switching)', 'High (replay buffer)', 'Limited'
    ]
})

print('\n', comparison.to_string(index=False))
comparison.to_csv(f'{SAVE_DIR}/comparison_table.csv', index=False)
print('\nTable saved to Drive.')